# Generated by Django 5.1 on 2024-08-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
